// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPH8Xbl3cG6kPjKYVNoCLTOJT0oJDKOnM',
    appId: '1:349199270045:web:9ae8fe115dd5bb3137d474',
    messagingSenderId: '349199270045',
    projectId: 'gdsc-chat-app-64ad1',
    authDomain: 'gdsc-chat-app-64ad1.firebaseapp.com',
    storageBucket: 'gdsc-chat-app-64ad1.appspot.com',
    measurementId: 'G-RV6MNZGHNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5nAuEyS20E6dPGjNWqOV5iqCRC7lIuxE',
    appId: '1:349199270045:android:31f248317d800dc837d474',
    messagingSenderId: '349199270045',
    projectId: 'gdsc-chat-app-64ad1',
    storageBucket: 'gdsc-chat-app-64ad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP3SbqPCnnijOdbCuw0ocSvweWyDiNmdw',
    appId: '1:349199270045:ios:d6b7ff3403c3a93b37d474',
    messagingSenderId: '349199270045',
    projectId: 'gdsc-chat-app-64ad1',
    storageBucket: 'gdsc-chat-app-64ad1.appspot.com',
    iosBundleId: 'com.example.flutterFireChatApp',
  );
}
